import React, { useState } from 'react';
import { 
  GitPullRequest, 
  ExternalLink, 
  Code2, 
  CheckCircle2, 
  Sparkles, 
  Search, 
  GitBranch, 
  Clock, 
  Filter 
} from 'lucide-react';
import { MOCK_PRS } from '../mockData';

export function PullRequestsScreen({ onViewDiff }) {
  const [filter, setFilter] = useState('ALL');
  const [search, setSearch] = useState('');

  const filteredPRs = MOCK_PRS.filter(pr => {
    if (filter !== 'ALL' && pr.status.toUpperCase() !== filter) return false;
    if (search && !pr.title.toLowerCase().includes(search.toLowerCase()) && !pr.ticketId.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Top Header Card */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-6 shadow-sm flex items-center justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-slate-900 tracking-tight">
            GitHub Pull Requests
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Browse and review pull requests generated by the autonomous AI software engineering agent.
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-3">
          <div className="flex items-center bg-slate-100 p-1 rounded-xl border border-slate-200 text-xs font-bold">
            {['ALL', 'OPEN', 'MERGED'].map(f => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-3 py-1.5 rounded-lg transition-all ${
                  filter === f ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                {f}
              </button>
            ))}
          </div>

          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search PRs or tickets..."
              className="pl-9 pr-3 py-1.5 text-xs bg-white border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 w-52"
            />
          </div>
        </div>
      </div>

      {/* PRs Table / List */}
      <div className="bg-white border border-slate-200/90 rounded-2xl overflow-hidden shadow-sm">
        <div className="divide-y divide-slate-100">
          {filteredPRs.map((pr) => (
            <div key={pr.id} className="p-5 hover:bg-slate-50/70 transition-all flex items-center justify-between gap-4 flex-wrap">
              <div className="flex items-start gap-4 max-w-3xl">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 mt-1 ${
                  pr.status === 'Merged' ? 'bg-purple-100 text-purple-700' : 'bg-emerald-100 text-emerald-700'
                }`}>
                  <GitPullRequest className="w-5 h-5" />
                </div>

                <div className="space-y-1.5">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-xs font-mono font-bold text-blue-600 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">
                      {pr.ticketId}
                    </span>
                    <span className="text-sm font-bold text-slate-900">
                      {pr.title}
                    </span>
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                      pr.status === 'Merged' ? 'bg-purple-100 text-purple-800' : 'bg-emerald-100 text-emerald-800'
                    }`}>
                      {pr.status}
                    </span>
                    {pr.healed && (
                      <span className="text-[10px] font-bold text-amber-700 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-full flex items-center gap-1">
                        <Sparkles className="w-2.5 h-2.5" /> Self-Healed
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-slate-500 line-clamp-1">{pr.summary}</p>

                  <div className="flex items-center gap-4 text-[11px] text-slate-500 pt-1">
                    <span className="flex items-center gap-1 font-mono">
                      <GitBranch className="w-3 h-3 text-slate-400" />
                      <span>{pr.branch}</span>
                      <span className="text-slate-300">→</span>
                      <span>{pr.base}</span>
                    </span>
                    <span>Repo: <strong>{pr.repo}</strong></span>
                    <span className="font-mono text-emerald-600 font-semibold">+{pr.additions} -{pr.deletions}</span>
                    <span className="flex items-center gap-1 text-slate-400">
                      <Clock className="w-3 h-3" />
                      <span>{pr.createdAgo}</span>
                    </span>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0">
                <button
                  onClick={() => onViewDiff && onViewDiff(pr.ticketId)}
                  className="flex items-center gap-1.5 text-xs font-bold text-slate-700 bg-white hover:bg-slate-100 px-3.5 py-2 rounded-xl border border-slate-200 shadow-sm transition-all"
                >
                  <Code2 className="w-3.5 h-3.5 text-blue-600" />
                  <span>View Diff</span>
                </button>

                <a
                  href={pr.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-xl shadow-sm shadow-blue-500/20 transition-all"
                >
                  <span>Open on GitHub</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
